-- PROGRAM 1: LIBRARY
-- 1
SELECT B.BOOK_ID, B.TITLE, B.PUBLISHER_NAME, A.AUTHOR_NAME, C.NO_OF_COPIES, L.BRANCH_ID
FROM BOOK B, BOOK_AUTHORS A, BOOK_COPIES C, BOOK_LENDING L
WHERE B.BOOK_ID = A.BOOK_ID
AND B.BOOK_ID = C.BOOK_ID
AND C.BRANCH_ID = L.BRANCH_ID;

-- 2
SELECT CARD_NO
FROM BOOK_LENDING
WHERE DATE_OUT BETWEEN '01-JAN-2017' AND '30-JUN-2017'
GROUP BY CARD_NO
HAVING COUNT(*) > 3;

-- 3
DELETE FROM BOOK
WHERE BOOK_ID = 3;

-- 4
CREATE VIEW BOOK_PUBLICATION_VIEW AS
SELECT PUB_YEAR
FROM BOOK;

-- 5
CREATE VIEW BOOK_COPIES_AVAILABLE AS
SELECT B.BOOK_ID, B.TITLE, C.NO_OF_COPIES
FROM BOOK, NO_OF_COPIES
WHERE B.BOOK_ID = 
