-- PROGRAM 2: ORDERS
-- 1
SELECT GRADE, COUNT(DISTINCT CUSTOMER_ID)
FROM CUSTOMER_ID
GROUP BY GRADE
HAVING GRADE > (SELECT AVG(GRADE)
                FROM CUSTOMER
                WHERE CITY='BANGALORE');

-- 2
SELECT SALESMAN_ID, NAME
FROM SALESMAN
WHERE 1 < (SELECT COUNT(*)
            FROM CUSTOMER
            WHERE SALESMAN_ID = A.SALESMAN_ID);

-- 3
